## -*- makefile -*-
##
## Include file for automake
##
## Copyright (C) 2008, 2009 Francesco Salvestrini
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.,
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
##

##
## Maintainer related targets
##

BUILT_SOURCES += $(top_srcdir)/.version

$(top_srcdir)/.version:
	echo $(VERSION) > $@-t && mv $@-t $@

dist-hook-version:
	echo $(VERSION) > $(distdir)/.tarball-version

EXTRA_DIST += $(DNT_DB) AUTHORS.in

TODO: $(DNT_DB)
	$(DNT_BIN)				\
	       --database=$(DNT_DB)		\
	       --mono				\
	       show				\
	       --filter="not done"		\
	       --line-format="* %t"		\
	       --width=78			\
	       --indent-fill=""			\
	       --unindent-fill=""		\
	       --level-fill=""			\
	       --output=TODO || {		\
		rm -f TODO ;			\
		exit 1 ;			\
	}
MAINTAINERCLEANFILES += TODO
EXTRA_DIST           += TODO

.releases:
	$(GITTAG_TO_DATE) > .releases || {	\
		rm -f .releases ;		\
		exit 1 ;			\
	}
MAINTAINERCLEANFILES += .releases
EXTRA_DIST           += .releases

NEWS: $(DNT_DB) .releases
	DNT_BIN="$(DNT_BIN)"			\
	DNT_DB="$(DNT_DB)"			\
	$(RELEASES_TO_NEWS) .releases NEWS || {	\
		rm -f NEWS ;			\
		exit 1 ;			\
	}
MAINTAINERCLEANFILES += NEWS
EXTRA_DIST           += NEWS

AUTHORS:
	rm -f AUTHORS                       &&				   \
	touch AUTHORS                       &&				   \
	cat $(srcdir)/AUTHORS.in >> AUTHORS &&				   \
	$(GITLOG_TO_COMMITTERS) | $(SED) -e 's,\(.*\),  \1,' >> AUTHORS && \
	echo "" >> AUTHORS                  || {			   \
	        rm -f AUTHORS ;						   \
	        exit 1 ;						   \
	}
MAINTAINERCLEANFILES += AUTHORS
EXTRA_DIST           += AUTHORS

ChangeLog:
	$(GITLOG_TO_CHANGELOG) > ChangeLog || {	\
		rm -f ChangeLog ;		\
		exit 1 ;			\
	}
MAINTAINERCLEANFILES += ChangeLog
EXTRA_DIST           += ChangeLog

dist-hook-bootstrap:
	chmod a-x $(distdir)/bootstrap

dist-hook-files: NEWS TODO ChangeLog AUTHORS dist-hook-bootstrap

dist-hook: dist-hook-version dist-hook-files

dist-gpg: dist
	gpg --yes -b --use-agent					   \
		-o $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig	   \
		$(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz          &&   \
	gpg --verify $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig || { \
		rm -f $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig ;   \
		exit 1 ;						   \
	}
MAINTAINERCLEANFILES += $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig

dist-upload: dist-gpg
	chmod 644 $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz     &&	\
	chmod 644 $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig &&	\
	scp $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz		\
	    $${USER}@dl.sv.nongnu.org:/releases/grmrextractors     &&	\
	scp $(PACKAGE_TARNAME)-$(PACKAGE_VERSION).tar.gz.sig		\
	    $${USER}@dl.sv.nongnu.org:/releases/grmrextractors     || {	\
		exit 1 ;						\
	}

announcement:
	$(ANNOUNCE_GEN)				\
	  --release-type=alpha			\
	  --package=$(PACKAGE_TARNAME)		\
	  --prev=$(PACKAGE_VERSION).test	\
	  --curr=$(PACKAGE_VERSION)		\
	  --gpg-key-id=TEST			\
	  --url-dir=TEST
